### ISSUE TITLE
standard-deviation, average and benchmarks

### ISSUE THREAD

**Issue by GoogleCodeExporter** [theseion/Fuel#106]
```
benchmarks samples should be run several times, we should get the average and 
then get the standard-deviation. 

For more details, read the mail: "Question about benchmark graph"
```

Original issue reported on code.google.com by `marianopeck` on 14 Oct 2011 at 7:01

**Comment by tinchodias** [comment]
This was done. If my memory doesn't fail, we pair-programmed with @theseion in RMOD the migration of benchmarks to [SMark](https://github.com/smarr/SMark).

However, [the dependency](https://github.com/theseion/Fuel/blob/412ef093b2aed063b9293ca8d16ede33737b726e/repository/BaselineOfFuel.package/BaselineOfFuel.class/instance/smark..st) looks outdated now, as it's pointing to a `ConfigurationOfSMark` in "http://smalltalkhub.com/mc/StefanMarr/SMark/main"... But that's another issue.
