### ISSUE TITLE
we should put nice charts in the website comparint to other serializers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [theseion/Fuel#124]
```
as we did in the paper but with nice colors and an explanation.
```

Original issue reported on code.google.com by `marianopeck` on 14 Dec 2011 at 7:54

**Comment by tinchodias** [comment]
I would close this issue, too old. It is not bad idea anyway... there are other new serializers available in Pharo to compare with. Do we close it @theseion ?

**Comment by tinchodias** [comment]
Let's close this, it can be reopened in any case. I think this would be part of a documentation rewriting.
