### ISSUE TITLE
Introduce configurable limit to number of objects serialized

### ISSUE THREAD

**Issue by GoogleCodeExporter** [theseion/Fuel#203]
```
I serialize stacks in our production images. Sometimes these stacks become very 
big (just had one with 16MB). Since cutting off the stack isn't necessarily a 
solution (the first few contexts can reference the entire graph) I thought that 
we could maybe introduce a configurable limit for the number of objects that 
are to be serialized.

Something like this:

analyzer := FLAnalyzer newDefault
    objectLimit: 50000;
    yourself.
FLSerializer newDefault
    analyzer: analyzer;
    ...

When the serialization reaches the limit it will discard the stack of untraced 
objects and replace invalid references with nil.

Thoughts?
```

Original issue reported on code.google.com by `maxle...@gmail.com` on 31 May 2013 at 8:50

**Comment by theseion** [comment]
I have an idea of how to do this but it requires changes to various parts of the code. I have a simple prototype which still fails for more complex cases.

Theory: think of the graph as a network of nodes that are grouped around the root node in concentric circles. Every circle represents a one step increase of distance to the root node.
To constrain the number of objects in the graph sensibly, simply prune nodes with distance > x. This even works for context chains.

**Comment by tinchodias** [comment]
Do the changes to various parts of the code of your working prototype also increase complexity to understand the code, or are they just spread changes? If it's more close to the first option, then you can just commit it, IMO.

**Comment by theseion** [comment]
Yes, I believe they do. I'm not happy with the code. First I want to have a prototype that works across all cases, then I can try to make it pretty.

**Comment by theseion** [comment]
@theseion In 4.0.0 (finally ;))
