### ISSUE TITLE
Substitution of the root node does not work

### ISSUE THREAD

**Issue by theseion** [theseion/Fuel#209]
`s := ByteArray new writeStream.
serializer := FLSerializer newDefault.
    serializer analyzer 
        when: [ :o | o==Array ] 
        substituteBy: [ :o |  #instead ].
  serializer serialize: {Array} on: s
.
s2 := s contents readStream.

object := (FLMaterializer newDefault materializeFrom: s2) root.`

**Comment by theseion** [comment]
The problem is that the substitution replaces *all* references. That includes references to classes used by clusters. Whenever a class is replaced of which an instance is present in the graph Fuel will have trouble during serialization because the cluster of that class will use the substitute when trying to instantiate an instance.

**Comment by theseion** [comment]
Fix description from commit:

> do not replace indexes directly when using the pluggable substituation but store track substitution indexes separately in the encoder. That enables us to still encode references to the classes used by the clusters while substituting all other objects

**Comment by tinchodias** [comment]
Nice thnks!
