### ISSUE TITLE
Split FuelPlatform into per platform packages

### ISSUE THREAD

**Issue by theseion** [theseion/Fuel#211]
It's ugly to load all the unnecessary code for all other platforms when loading FuelPlatform. We should split FuelPlatform into FuelPlatform-Core, -Pharo and -Squeak. It should be straight forward to check in the configuration which packages we need to load (note that we can't use the usual configuration specs in this case).

**Comment by tinchodias** [comment]
+1 
then we can avoid the noise in the terminal when loading fuel (I have it when loading Voyage)

**Comment by theseion** [comment]
> On 29 Apr 2016, at 10:07, Martín Dias <notifications@github.com> wrote:
> 
> +1 
> then we can avoid the noise in the terminal when loading fuel (I have it when loading Voyage)
> 
> 

That should already be better because I fixed all unreferenced variable warnings.

**Comment by marianopeck** [comment]
Yes, this is a good idea.

**Comment by theseion** [comment]
Yay, done :) (Version 2.1.8)

**Comment by tinchodias** [comment]
Great Max! thanks
