### ISSUE TITLE
Serializing special objects like nil, true, false together with classes when they have to be substituted

### ISSUE THREAD

**Issue by dionisiydk** [theseion/Fuel#217]
Serializing special objects like nil, true, false together with classes not working when classes needs substitution. Following code is broken:

buffer := ByteArray streamContents: [ :s | 	
	serializer := FLSerializer newDefault.
	serializer analyzer 
        when: [ :o | o == UndefinedObject] 
        substituteBy: [ :o | 100 ].
   serializer serialize: {nil. UndefinedObject} on: s].
	
object := (FLMaterializer newDefault materializeFrom: buffer readStream) root.

And for booleans:

buffer := ByteArray streamContents: [ :s | 	
	serializer := FLSerializer newDefault.
	serializer analyzer 
        when: [ :o | o == True] 
        substituteBy: [ :o | 100 ].
   serializer serialize: {true. True} on: s].
	
object := (FLMaterializer newDefault materializeFrom: buffer readStream) root.

**Comment by dionisiydk** [comment]
Same for Character:

buffer := ByteArray streamContents: [ :s |

serializer := FLSerializer newDefault.
serializer analyzer 
when: [ :o | o == Character] 
substituteBy: [ :o | 100 ].
serializer serialize: {$e. Character} on: s].

object := (FLMaterializer newDefault materializeFrom: buffer readStream) root.

**Comment by marianopeck** [comment]
Yes, this limit was kind of a design decision. Maybe we didn't expect someone wanting to substitute nil, true, false, characters, etc.

**Comment by dionisiydk** [comment]
But this case not about true, false and nil substitution but about classes substitution. Is it same?

**Comment by tinchodias** [comment]
I found the problem and fixed it. Now, there is so much time that I don't contribute with code to Fuel that I'm sure what's the best repository to commit! This is the fix:

Use encodeReferenceToClusterObjectClass: instead of encodeReferenceTo:, in the same way as FOObjectCluster>>clusterSerializeStepWith: does:


FLHookPrimitiveCluster>>
clusterSerializeStepWith: aSerialization

	super clusterSerializeStepWith: aSerialization.
	aSerialization encoder encodeReferenceToClusterObjectClass: theClass.

**Comment by tinchodias** [comment]
I was not sure if Fuel supported this, but I saw that #testPrivateExcludedAndWithConflicts reproduces more or less Denis' case but with a regular class instead of a "primivite class". BTW, we should crate the test now.

**Comment by tinchodias** [comment]
Very related with issue #209

**Comment by tinchodias** [comment]
Done. Released version 2.1.6 in sthub/Pharo/Fuel, with fix and tests. Now it needs to be integrated into pharo 6 (or 5 too?)

**Comment by dionisiydk** [comment]
Thank's.

2016-06-13 21:26 GMT+02:00 Martín Dias <notifications@github.com>:

**Comment by tinchodias** [comment]
i guess we can close this issue. Did you integrate the new version, Denis?

**Comment by dionisiydk** [comment]
Not yet. I was at vacation

2016-06-20 18:13 GMT+02:00 Martín Dias <notifications@github.com>:

**Comment by dionisiydk** [comment]
I open issue 18545 <https://pharo.fogbugz.com/f/cases/18545/Update-Fuel>

2016-06-20 18:15 GMT+02:00 Denis Kudriashov <dionisiydk@gmail.com>:

**Comment by dionisiydk** [comment]
In 60100

2016-06-20 18:19 GMT+02:00 Denis Kudriashov <dionisiydk@gmail.com>:
