### ISSUE TITLE
Substitutions during CompiledMethod serialization are not working

### ISSUE THREAD

**Issue by dionisiydk** [theseion/Fuel#218]
Try following test:

    method := (Point>>#extent:).

    buffer := ByteArray streamContents: [ :s | 
	    serializer := FLSerializer newDefault.
	    serializer analyzer 
            when: [ :o |  o==Rectangle] 
            substituteBy: [ :o | #substitutedGlobal ].
        serializer serialize: method on: s ].

    methodAfter := (FLMaterializer newDefault materializeFrom: buffer readStream) root.

    (methodAfter literalAt: 1) value == #substitutedGlobal "--> false"

But you will serialise copy of method this test is working

**Comment by theseion** [comment]
I think you may be right. Looking at the code it seems that this is a side-effect of the cluster hierarchy i.e., the cluster for installed compiled methods does not trace the literals and thus does not support substitution.
No wait… :confused:

[2:14]  
Ok, so this is the desired behaviour I think. If the compiled method is installed, that means that there will be the exact same compiled method in the image in which we materialize in. Therefore all literals will be the same and hence the bindings of globals will be correct too. So there is no need to serialize the subgraph of the compiled method.

[2:14]  
All the information you need is how to look up the corresponding compiled method when materializing.

-----------
Closing this as invalid. Maybe we'll need to enable customised serialisation of CompiledMethods in the future.
