### ISSUE TITLE
Change in the number of superclass variables causes error during materialization of class

### ISSUE THREAD

**Issue by theseion** [theseion/Fuel#221]
1. serialize a class with an instance variable
2. add an instance variable to its superclass
3. materialize the class -> #primitiveFailed

The format materialized for the class is no longer valid and thus the primitive for writing to instance variables can fail.

**Comment by theseion** [comment]
fixed

**Comment by tinchodias** [comment]
This was in Metalevel Fuel, wasn't it?

**Comment by theseion** [comment]
Yes.
