### ISSUE TITLE
64-bit adaptations

### ISSUE THREAD

**Issue by theseion** [theseion/Fuel#224]
See https://pharo.fogbugz.com/f/cases/20120:

There are several problems under 64 bits, mainly because `SmallInteger` has up to 61 bits, and because of `SmallFloat64`.

See method `#clusterClassForSmallInteger:` that only works for 31 bits SmallInteger.
See also `Float class>>materializeFrom:` which might try to write into a `SmallFloat64` and fail.

I would write something like:

```smalltallk
materializeFrom: aDecoder
    ^ (BoxedFloat64 new: 2)
        at: 1 put: aDecoder nextEncodedUint32;
        at: 2 put: aDecoder nextEncodedUint32;
        * 1.
```

The * 1 is here to give a chance to the VM to create a `SmallFloat64` if it can.

**Comment by theseion** [comment]
@marianopeck @tinchodias This issue has become an important problem (see mailing list). If one of you could start to work on it that would be great. I will be on holiday next week and have no time this week.

**Comment by tinchodias** [comment]
oh, ok. Thursday/Friday evening I could check.

**Comment by tinchodias** [comment]
Yesterday, I wrote in the fogbugz case with a fix.

**Comment by theseion** [comment]
Thanks a lot @tinchodias! Great work.

**Comment by tinchodias** [comment]
Max, I forgot to say that when I commit the fix, travis showed some problems in squeak build... it was some expectedFailures that were green. I didn't investigate though.

**Comment by theseion** [comment]
I'm aware of that. It's because of a fix to the handling of WideString instances.

**Comment by noha** [comment]
What's the status on this?

**Comment by theseion** [comment]
I'm on it.

**Comment by theseion** [comment]
In Pharo with https://github.com/pharo-project/pharo/pull/654
