### ISSUE TITLE
Remove Pharo 6 platform class from Pharo 7

### ISSUE THREAD

**Issue by theseion** [theseion/Fuel#227]

**Comment by astares** [comment]
Would it be possible to implement it that way that it does not need to be updated each Pharo version?
Or at least have a test that checks that it fits to the current Pharo version so we can adopt it each time...

Thanks for caring!

**Comment by theseion** [comment]
Yeah, that's an open problem. I've opened an [issue](#228) so I don't forget.

**Comment by theseion** [comment]
I modified the title of the issue, as the platform classes for Squeak 6 and Pharo 7 have already existed for quite a long time. The issue is actually about the extraneous Pharo 6 platform class in Pharo 7.

**Comment by theseion** [comment]
See https://pharo.fogbugz.com/f/cases/20970/Remove-Pharo-6-platform-class-from-Pharo-7
