### ISSUE TITLE
Add helps to the debug actions

### ISSUE THREAD

**Issue by jecisc** [theseion/Fuel#230]
I am currently adding helps (displayed in tooltips) to all debug actions because newbies complained that the "No help, sorry." tooltip was not useful. Those changes includes a Fuel action. Should they be sync with this repository?

Che change consist of adding:

```Smalltalk
FuelOutStackDebugAction>>help
	^ 'Serialize a portion of the current stack trace using fuel.'
```

**Comment by tinchodias** [comment]
Thanks for the contribution. It's OK if you did it in Pharo repo... We are in middle of migration from sthub to this repo and will need to sync with other changes there. 

Then, ideally Pharo bootstrap will load the project from here.

**Comment by theseion** [comment]
The migration is complete. I'll integrate that method.

**Comment by jecisc** [comment]
Thank you! :)
