### ISSUE TITLE
Fuel package present in Pharo but not loaded

### ISSUE THREAD

**Issue by jecisc** [theseion/Fuel#233]
In the Pharo repository, there is a Fuel package containing extension methods. 

This package is not loaded because not present in the baselines. 

It should either be removed from the repository or be added to the baseline. Or the extensions should be moved to another package.

https://github.com/pharo-project/pharo/tree/development/src/Fuel

**Comment by theseion** [comment]
Thanks!
Fixed in https://github.com/pharo-project/pharo/pull/2122
