### ISSUE TITLE
Pharo 7: error in Set>>#addIfNotPresent:ifPresentDo:

### ISSUE THREAD

**Issue by tinchodias** [theseion/Fuel#242]
There is an DNU if you use this method, which sends `#asCollectionElement` instead of `#asSetElement`. 

I'm loading Fuel from Voyage, which loads ImageWorker with:

~~~
imageWorker: spec
	spec baseline: 'ImageWorker' with: [ 
		spec
			repository: 'github://pharo-contributions/ImageWorker/source' ]
~~~

which loads Fuel-Metalevel with:

~~~
fuelMetalevel: spec
	spec baseline: 'Fuel' with: [ 
		spec 
			repository: 'github://theseion/Fuel/repository';
			loads: #( 'Fuel-Metalevel' ) ]
~~~

**Comment by tinchodias** [comment]
I've looked at the code to recall a bit and learn more of the FuelPlatform project.
The coode that's broken in master+pharo7 is:
~~~Smalltalk
Set>>
addIfNotPresent: anObject ifPresentDo: aBlock
	"Include anObject as one of the receiver's elements and then value aBlock, but only if there
	is no such element already. Anwser anObject."

	| index |
	index := self scanFor: anObject.
	(array at: index) 
		ifNil: [self atNewIndex: index put: anObject asCollectionElement]
		ifNotNil: [ aBlock value ].
	^ anObject
~~~
Alternatives:
1. Remove the override in Set and let the unoptimized implementation in Collection.
2. Make this method a extension of the installed platform. Fuel-Platform-Pharo7 will have the optimized version that uses `asSetElement` and the -Pharo8 will have the `asCollectionElement`.

Any suggestion, @theseion :)?

**Comment by tinchodias** [comment]
We should had proposed merging into the Pharo some methods like this that Fuel has... I'd do this for Pharo 8/9.

**Comment by theseion** [comment]
Master shouldn't be loaded into projects and as Pharo 8 (soon 9) is the development platform no other platform should be expected to work with master. Also, until somebody finally fixes the Pharo VM build for Linux I'm not going to do anything as I can't run the tests on TravisCI.

3.0.1 should work for Pharo 7, as the last build for 3.0.1 on TravisCI shows: https://travis-ci.org/theseion/Fuel/builds/491209340.

As for `#asSetElement`, that should keep working for Pharo 7 and Pharo 8 once we release a new version, I think.

Maybe I misunderstood your question though.

**Comment by theseion** [comment]
I've looked at this again and I'm still convinced that you shouldn't load master into Pharo 7. However, you are correct in that 3.0.2 sends `#asCollectionElement` in Pharo 7 but shouldn't. Nice find. I guess we never saw that because we couldn't run the tests...
3.0.1 is not affected.

**Comment by theseion** [comment]
Fixed. I've added extensions for `#asCollectionElement` to the platform class.
