### ISSUE TITLE
FLDelayedSerializationMock DNU when Serializing

### ISSUE THREAD

**Issue by seandenigris** [theseion/Fuel#257]
The following script:
```smalltalk
FLSerializer new
		object: 1;
		fileName: (FileLocator home / '1.fuel') fullName;
		serialize.
```
led to this error:
<img width="970" alt="Screen Shot 2021-11-14 at 1 56 18 PM" src="https://user-images.githubusercontent.com/184176/141694556-77de5587-53d3-4d79-95de-8e8e42871cc4.png">

Implementing this on `FLDelayedSerializationMock` avoided the error, but not sure of other implications:
```smalltalk
isResponsible
	^ false
```

Fuel 4.0.0 on P9 (GT actually)

**Comment by theseion** [comment]
How did you load the project? That method is simply a method on `FLDelayedSerializationModk`, which is in `Fuel-Test-Core`. Your example works for me.

**Comment by seandenigris** [comment]
I loaded it in an image where 3.0.3 was already loaded. Could that be a factor? I’ll try a fresh image

**Comment by theseion** [comment]
The baseline includes a hack that first unloads a loaded Fuel. I know that works because we run all our tests in Pharo by simply loading the baseline. The only difference I can see so far is GT.

**Comment by seandenigris** [comment]
Yes, I confirm. I get the error in GT, but not P9. Not sure what the difference is. Checking the references of `BaselineOfFuel` in GT, there is:
```smalltalk
"BaselineOfIDE"
		spec baseline: 'Fuel' with: [ 
			spec
				repository: repository;
				loads: #( 'Tests' ) ].
```
and
```smalltalk
"BaselineOfMorphic"
		spec baseline: 'Fuel' with: [ 
			spec repository: repository; loads: #('Core') ].
```
which are the same in Pharo 9. Although, maybe the value of `repository` is different? Perhaps @girba could shed some light...

**Comment by theseion** [comment]
Do you load GT into the image manually or do you use a prepared image? Can you post the instructions for either so I can try to reproduce?

**Comment by seandenigris** [comment]
```smalltalk
Metacello new
    repository: 'github://theseion/Fuel:4.0.0';
    baseline: 'Fuel';
    load.
```

**Comment by theseion** [comment]
The reason this loads differently in GT is that GT explicitly loads `#Tests`. Metacello will detect a load conflict and will not load the new version. In Pharo that package is probably not registered (my guess is that the release process cleans out the Metacello registry), so it looks like `#Tests` is something new to load.

In any case, here's the invocation to make it work in GT:
```smalltalk
Metacello new
    repository: 'github://theseion/Fuel:4.0.0';
    baseline: 'Fuel';
    onWarning: [ :ex |
    	ex class == MCMergeOrLoadWarning
    		ifTrue: [ ex load ]
    		ifFalse: [ ex resume ] ];
    load: #Tests
```

**Comment by seandenigris** [comment]
Thanks. I requested GT to upgrade to 4.0.0 which seems to be the simplest fix
