### ISSUE TITLE
Header, Writing To

### ISSUE THREAD

**Issue by seandenigris** [theseion/Fuel#260]
Following [the docs](https://theseion.github.io/Fuel/builtin-header-support/), I did:
```smalltalk
serializer := FLSerializer new.
	serializer header 
		at: #spFormatVersion
		putAdditionalObject: SpFileDatabase formatVersion.
```
 but, `FLSerializer` DNU `#header`. I noticed that `FLSerializer` implements `#at:putAdditionalObject:`, so I tried that, but my image hung.

**Comment by theseion** [comment]
Those docs are outdated for version 4. You should use `#at:putAdditionalObject:`. See `FLFullHeaderSerializationTest>>testJustMaterializeHeader` and `#testAdditionalObjects` for reference. From the top of my head I don't see why the image should hang but maybe there's a recursion issue there.

**Comment by theseion** [comment]
Not stale.

**Comment by seandenigris** [comment]
I’ll try again in 5.0.1

**Comment by seandenigris** [comment]
The following works in P9 and GT 0.8.1395 with Fuel 5.0.1:
```smalltalk
filePath := (FileLocator imageDirectory / 'obj.fuel') fullName.
FLSerializer new
	at: #spFormatVersion
		putAdditionalObject: '1.0.3';
	object: 3;
	filePath: filePath;
	serialize.
		
materialization := FLMaterializer new
	filePath: filePath;
	materialize.
```

**Comment by theseion** [comment]
Thanks @seandenigris.
