### ISSUE TITLE
Talents with multiple instance variables lose some of them

### ISSUE THREAD

**Issue by theseion** [theseion/Fuel#262]
See https://github.com/tesonep/pharo-talents/issues/11

**Comment by theseion** [comment]
I have a working fix. Need to clean it up. Will hopefully release the new version tomorrow.

**Comment by theseion** [comment]
@seandenigris I've released 5.0.0 with the necessary changes. I'm eagerly awaiting more bug reports :p.

**Comment by seandenigris** [comment]
Thanks for this! Can't wait to try it out tomorrow...

**Comment by seandenigris** [comment]
I confirm Fuel 5.0.1 fixes the issue. Thanks again everyone 🥳
