### ISSUE TITLE
FLVersion Caching

### ISSUE THREAD

**Issue by seandenigris** [theseion/Fuel#263]
I wonder if the current version should be lazily initialized as in https://github.com/theseion/Fuel/blob/e44dd4b327dcaf69d1e74063e13df0fbeabc5364/repository/Fuel-Core.package/FLVersion.class/class/current.st

The version seems to be a rather cheap to create value object and the version may change (i.e. loading a newer Fuel version). I upgraded Fuel and was confused when serialization still stored the prior version and thus was un-materialize-able in my new image.

What about just
```smalltalk
current
	^ self
			newWithMajor: 5
			minor: 0
			patch: 1
```
maybe without even the class var...

**Comment by tinchodias** [comment]
+1  without the class var

**Comment by theseion** [comment]
Hm... yeah... 😅
