### ISSUE TITLE
FLPlatform class>>#removeModifications is dead code

### ISSUE THREAD

**Issue by MarcusDenker** [theseion/Fuel#271]
We are working on a huge cleanup in Pharo12 to improve how packages are modelled.

Backward compatibility will not be the main goal of that improvement.

With the "Same code base for all version on Pharo" philosophy, this will be a true challenge to do for Fuel to follow this change while being loadable in old versions.

We are doing the changes in Pharo12, changing Fuel as we go along as everything else would make this change impossible.

This PR: https://github.com/pharo-project/pharo/pull/13259

removes 

- Platform class >> hacksCategoryName (dead code)
- Platform class >> removeModifications (dead code)
- all #isResponsibleForCurrentPlatform (dead code after removing removeModifications

**Comment by theseion** [comment]
Done.

**Comment by theseion** [comment]
In https://github.com/pharo-project/pharo/pull/14132
