### ISSUE TITLE
[Pharo11] We now have Ephemerons in Pharo11

### ISSUE THREAD

**Issue by MarcusDenker** [theseion/Fuel#272]
Pharo11 now implemens Ephemerons and uses it to implement Weak datastructures.

Fuel seems to not support serializing them.

I would implement this by forwarding to the Class Layout, but of course Fuel can no do that because it wants to be source level backward compatible to systems that do not have the class layout hierarchy... 

```
fuelAccept: aGeneralMapper

	"Be careful because the order is important. For example, weak are also variable, but we need that weak objects send #visitWeakObject: and not #visitVariableObject: "
	self class isFixed
		ifTrue: [ ^ aGeneralMapper visitFixedObject: self ].
	self class isWeak
		ifTrue: [ ^ aGeneralMapper visitWeakObject: self ].
	self class isPointers
		ifTrue: [ ^ aGeneralMapper visitVariableObject: self ].
	self class isBytes
		ifTrue: [ ^ aGeneralMapper visitBytesObject: self ].
	self class isWords
		ifTrue: [	^ aGeneralMapper visitWordsObject: self ].
	self error: 'Something is wrong!'
```

**Comment by tinchodias** [comment]
There is `FLPlatform current` that returns e.g. an instance of `FLPharo11Platform`, or the corresponding one. What should be moved there to support ephemerons?

**Comment by theseion** [comment]
@tinchodias, same here, Fuel-Platform is no longer in Pharo 12+. We can implement this however we want.

**Comment by tinchodias** [comment]
I'm still not familiar with the ephemerons. I see in my Pharo 12 image:
```
Smalltalk allClasses select: [ :each | each isEphemeronClass ]
">>> an OrderedCollection(FinalizationRegistryEntry IllEphemeron WeakKeyAssociation)"
```
I'm not sure what should fuel serializer do when it finds an instance of those classes.

For example:
```
Association << #FinalizationRegistryEntry
	layout: EphemeronLayout;
	slots: { #container . #link };
	tag: 'Registry';
	package: 'System-Finalization'
```

Probably it should serialize ignore what is referenced in `container` and `link` slots.

The implementation for the variable weak objects was ignoring the objects pointed from the variable slots, but not serializing the fixed slots as if it was a regular object.

**Comment by theseion** [comment]
I think we can handle Ephemerons the same way we do weak classes: attempt to serialize the references (might be `nil` during serialization if the GC has kicked in), making sure not to collect the references into a collection that references the key strongly.

**Comment by theseion** [comment]
I've updated the Pharo12 branch to delegate cluster determination to the class layout. Now we can implement support for ephemerons.

**Comment by theseion** [comment]
@tinchodias @MarcusDenker https://github.com/pharo-project/pharo/pull/15563
