### ISSUE TITLE
[Pharo12] Huge cleanup of the compiler and compiler API 

### ISSUE THREAD

**Issue by MarcusDenker** [theseion/Fuel#273]
We are cleaning the compiler and the compilation APIs in Pharo12.

Backward compatibility is explicitly not a goal, as compatibility was the reason for the mess that we had...

We are doing the changes in Pharo12 and change the Fuel version there are needed.

**Comment by tinchodias** [comment]
I wonder if maybe the new way to do it in `FLPharo12Platform`, and the old code in the other `FLPlatform` (tests already use `FLPlatform current` to create anonymous classes, traits, etc.).

**Comment by theseion** [comment]
@tinchodias, we already kicked out Fuel-Platform. I've decided that for Pharo 12+ it is not worth investing the required amount of work to ensure compatibility.

**Comment by theseion** [comment]
Closing this issue. Those changes are already in progress and I'm actively backporting and updating.
