### ISSUE TITLE
[Pharo12] Huge cleanup of the SystemCategories and RPacakge and the API in Pharo12

### ISSUE THREAD

**Issue by MarcusDenker** [theseion/Fuel#274]
As mentioned in https://github.com/theseion/Fuel/issues/271 :

We are working on a huge cleanup in Pharo12 to improve how packages are modelled.

Backward compatibility will not be the main goal of that improvement.

With the "Same code base for all version on Pharo" philosophy, this will be a true challenge to do for Fuel to follow this change while being loadable in old versions.

We are doing the changes in Pharo12, changing Fuel as we go along as everything else would make this change impossible.

**Comment by theseion** [comment]
Done.

**Comment by theseion** [comment]
Appears to be mostly done.
