### ISSUE TITLE
[Pharo12] Huge cleanup of the method categories/protocols/ClassOrganizer

### ISSUE THREAD

**Issue by MarcusDenker** [theseion/Fuel#275]
As mentioned in https://github.com/theseion/Fuel/issues/270, we are changing deeply the structure of classes: ProtocolOrganizer has been merged with ClassOrganizer, the goal is to simplify the API and move it to class descrition.

We do these changes in the Pharo12 branch and change Fuel as needed. 

Making a version of fuel that is source=level compatible to that and all old Pharo version might be possible but for sure will require lots of more workarounds in the FLPLatform hierarchy

**Comment by MarcusDenker** [comment]
ClassOrganizer now has been inlined into ClassDescription in Pharo12: https://github.com/pharo-project/pharo/pull/13861

This included more change to Fuel, removing the sends of "organization"

**Comment by theseion** [comment]
Done

**Comment by theseion** [comment]
In https://github.com/pharo-project/pharo/pull/14132
