### ISSUE TITLE
[Pharo 12] No sources embedded in trailers anymore

### ISSUE THREAD

**Issue by MarcusDenker** [theseion/Fuel#276]
CompiledMethodTrailer was able to encode sources in the trailer... but that lead to very complex code.

We are simplifying in Pharo12.

Sadly it is not possible to remove this and stay compatible. I even do not know how to structure Fuel code following the philosophy that there is just one code base loaded in all Pharo versions...

I am committing for now in the Fuel fork in the Pharo repositiory:

https://github.com/pharo-project/pharo/pull/13522
- change setTrailerWithSourceCode to use property
- remvove setTrailerWithNoSource

https://github.com/pharo-project/pharo/pull/13546
- reduce sender of #trailer in the tests

https://github.com/pharo-project/pharo/pull/13560
- do not reference CompiledMethodTrailer, do not use #copyWithTrailerBytes:

**Comment by MarcusDenker** [comment]
The final version now has a dedicatedm clearSourcePointer, see https://github.com/pharo-project/pharo/pull/13578

**Comment by theseion** [comment]
Done. Thanks!

**Comment by theseion** [comment]
In https://github.com/pharo-project/pharo/pull/14132
