### ISSUE TITLE
Debugging: Document Its Obsolescence

### ISSUE THREAD

**Issue by seandenigris** [theseion/Fuel#285]
The [docs](https://theseion.github.io/Fuel/debugging/) are out-of-date as they reference the old API, but the primary issue is that the debug hooks seem to have vanished.

After loading Fuel-Debug, there doesn't seem to be any implementors of `setDebug`. `FLDebugMaterialization` is not referenced. Checking references of `FLMaterialization `, I found the apparent place to manually hack in debugging:
<img width="430" alt="Screenshot 2023-10-17 at 6 11 25 AM" src="https://github.com/theseion/Fuel/assets/184176/f4ec3876-8303-4c1f-baba-c00b4cc5e21b">

but there should be a supported hook.

Also, I was not clear how the debug output is helpful or what to do with it:
<img width="517" alt="Screenshot 2023-10-17 at 6 13 05 AM" src="https://github.com/theseion/Fuel/assets/184176/dc1f9b58-e317-4a2e-8930-f47c71f8f443">

**Comment by theseion** [comment]
I've never really used the debug package myself. Never found it very useful. That's why I stopped supporting it.

**Comment by seandenigris** [comment]
Thanks for the explanation!

**Comment by seandenigris** [comment]
Maybe a disclaimer in the docs at the beginning of the debug section clarifying that it's no longer supported?

**Comment by theseion** [comment]
Yes, good idea.

**Comment by theseion** [comment]
https://theseion.github.io/Fuel/debugging/

**Comment by seandenigris** [comment]
Thanks!
