### ISSUE TITLE
Fuel Discussion?

### ISSUE THREAD

**Issue by seandenigris** [theseion/Fuel#286]
What is the best place to discuss Fuel? If there is none, maybe we can enable "Discussions" on this repo? I'm having a problem materializing some data, but it's unclear whether there is a Fuel bug or some other problem...

**Comment by theseion** [comment]
Discord? That's where Pharo stuff happens. If you don't have a Discord account we can also turn on GH discussions.

**Comment by seandenigris** [comment]
Discord works. I wasn't sure if you and the other Fuel contributors were on there
