### ISSUE TITLE
[Bug]: Materializing InstVar after Move to Different Trait

### ISSUE THREAD

**Issue by seandenigris** [theseion/Fuel#287]
In my [LivingLibrary project](https://github.com/seandenigris/Living-Library), there is a LlAuthoredWork class which has a `properties` instVar. @ralfbarkow is trying to migrate his data to a newer version, but this instVar just will not seem to materialize.

The only obvious code change which would affect this instVar is that the class previously directly used Magritte's MATPropertyOwner trait (excerpt from class definition [here](https://github.com/seandenigris/Living-Library/blob/586793bccc5e9da2b5107eb504f61b84f9666df4/src/LivingLibrary/LlAuthoredWork.class.st#L24)):
```smalltalk
Object subclass: #LlAuthoredWork
	uses: LlTLibraryItem + (MATPropertyOwner - {#editLepiterPageDescription}) + MpTAlphabetizable + QuTTranscriptable
```
and now uses `MATPropertyOwner` via a subtrait, `DbTDomainObject`, which inherits from `MATPropertyOwner`:
```smalltalk
Object subclass: #LlAuthoredWork
	uses: LlTLibraryItem + (DbTDomainObject - {#editLepiterPageDescription}) + MpTAlphabetizable + QuTTranscriptable
```

I did an experiment which confirmed that the data is still there, just not getting into the correct instVar:
<img width="1278" alt="Screenshot 2023-10-24 at 5 48 24 AM" src="https://github.com/theseion/Fuel/assets/184176/0bf560e3-5cd7-4cae-bd79-ef6487910088">

**Comment by theseion** [comment]
I wrote a test to try and replicate your issue (in Pharo 12 with the latest version of Fuel):

```smalltalk
testTraitInheritance
	| class instance result |
	class := self classFactory make: [ :builder |
		builder
			traitComposition: FLNormalStatefulTrait;
			name: #FLTraitInheritanceTestClass ].
	instance := class new.
	instance properties
		at: #key
		put: 'value'.

	self serialize: instance.
	instance := nil.
	self classFactory delete: class.
	class := self classFactory make: [ :builder |
		builder
			traitComposition: FLStatelessSupertrait;
			name: #FLTraitInheritanceTestClass ].
	
	result := self materialized.
	self assert: (result properties includesKey: #key)
```

```smalltalk
Trait << #FLNormalStatefulTrait
	slots: { #properties };
	tag: '';
	package: 'Fuel-Core-Tests'
```
```smalltalk
Trait << #FLStatelessSupertrait
	traits: {FLNormalStatefulTrait};
	slots: {};
	tag: '';
	package: 'Fuel-Core-Tests'
```

The test first creates a class that directly uses the stateful trait and then materializes the instance using another class where the stateful trait is a subtrait. The test works as expected. This could be related to the version of Fuel you're using.

**Comment by seandenigris** [comment]
Okay, thanks for that impressive effort! Let's mark closed for now unless we see it again with latest Fuel
