### ISSUE TITLE
SubscriptOutOfBounds error from FLDecoder>>#nextEncodedReference

### ISSUE THREAD

**Issue by seandenigris** [theseion/Fuel#295]
I've been using Fuel to serialize a model for a few years now. All of a sudden, about two weeks ago, I started getting the following error when trying to materialize. My Fuel version (5.2.1) hasn't changed, only the model data. Any ideas?

<img width="1715" alt="Screenshot 2024-10-07 at 8 24 34 PM" src="https://github.com/user-attachments/assets/54432002-93af-4c2a-bbfc-168ec1bf67b6">

**Comment by tinchodias** [comment]
What number is this "nextIndex" and what's the size of `object`?
I wonder if the index looks like an index of that `object` array, or no-way, it looks like parsing is corrupted.

**Comment by seandenigris** [comment]
`objects size = 1710159` and `index = 0`

**Comment by seandenigris** [comment]
The offending object turned out to be a corrupt IdentitySet. Not sure how that happened. The tally is 8 but there  are only 5 objects in the set. The following fixed it and allowed the serialized graph it was a part of to successfully materialize: `anIdentitySet := anIdentitySet asOrderedCollection asIdentitySet`. It was a bit scary that years of data seemed in jeopardy, but as usual Smalltalk came to the rescue because everything was open and accessible to investigation!

<img width="562" alt="Screenshot 2024-10-08 at 10 22 54 PM" src="https://github.com/user-attachments/assets/696dbbfd-dba3-4757-911b-18f8b9603b43">

**Comment by tinchodias** [comment]
Great @seandenigris, so the source of that corrupted IdentitySet is not Fuel, right?

**Comment by seandenigris** [comment]
I have no evidence that fuel created the problem
