### ISSUE TITLE
Test XStream

### ISSUE THREAD

**Issue by GoogleCodeExporter** [theseion/Fuel#4]
```
Once issue 3 is done...we should test XStream, but simply. Just using XStream. 

Then, in a future, we can try to use the marshaling feature of XStreams
```

Original issue reported on code.google.com by `marianopeck` on 24 Mar 2011 at 9:35

**Comment by theseion** [comment]
Nice idea but we don't have resources. In addition, XStreams has been around for ages and neither Squeak nor Pharo have managed to adopt them. If that changes we can revisit this.
