### ISSUE TITLE
Prune (or graft) by depth criterion

### ISSUE THREAD

**Issue by GoogleCodeExporter** [theseion/Fuel#44]
```
We want to prune (replace by nil) or graft (replace by another subgraph) the 
graph at some objects. 

The first criteria we will support are "the object is included in this 
collection" or "the object is instance of this class". 

But another interesting criteria we should explore is "depth is less than X" 
i.e. "distance from root is less than X".
```

Original issue reported on code.google.com by `tinchod...@gmail.com` on 16 Jun 2011 at 9:59

**Comment by theseion** [comment]
@tinchodias In 4.0.0 (finally! :))

**Comment by tinchodias** [comment]
Ohhhh! and 10 years has passed since first entry! haha :)

**Comment by theseion** [comment]
I remember struggling a lot with how this could be implemented. Turned out to be 30 minutes of coding. Just two pretty simple counters. I must have become wise... ;)
