### ISSUE TITLE
Hooks methods from  StOMP

### ISSUE THREAD

**Issue by GoogleCodeExporter** [theseion/Fuel#64]
```
http://stomp.smalltalk-users.jp/home/how-to-use-stomp/hook-methods

I would love to have ALL of them. In fact, some of them are NEEDED if we want 
to replace ImageSegment/ReferenceStream by Fuel in Pharo.

```

Original issue reported on code.google.com by `marianopeck` on 11 Jul 2011 at 8:51

**Comment by tinchodias** [comment]
The link to http://stomp.smalltalk-users.jp/home/how-to-use-stomp/hook-methods is broken!
Originally created in 2011 

We should close it
