### ISSUE TITLE
Partial loading

### ISSUE THREAD

**Issue by GoogleCodeExporter** [theseion/Fuel#8]
```
It would be cool if Fuel supports partial loading. So that it can materialize 
only one/few objects of a full serialized subgraph. 

Oracle Coherence has the nice feature of being indexed which allows for 
extracting values without deserializing the whole object graph (partial 
loading).

```

Original issue reported on code.google.com by `marianopeck` on 24 Mar 2011 at 9:53

**Comment by theseion** [comment]
Sounds very cool. However, the overhead of implementing and maintaining currently isn't justified by the few people using Fuel. We can revisit this if the need arises.
